name: Build and deploy Node.js app to Azure Web App - IoT-NodeRed-EnergyMeter

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # ✅ Zmieniono z "npm ci" na "npm install"
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3CBA8E005282451DB2912CF76432B3DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBCF5118567E4A80BEFFD0BFB26A26C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A9E875950664853B8367FC1DF5368A7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'IoT-NodeRed-EnergyMeter'
          slot-name: 'Production'
          package: .
