name: Build and deploy Node-RED app to Azure Web App - IoT-NodeRed-EnergyMeter

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 🔹 Zainstaluj WSZYSTKIE zależności
      - name: Install dependencies
        run: |
          npm ci
          npm install node-red-dashboard node-red-contrib-opcua
          npm rebuild

      # 🔹 Sprawdzenie poprawności builda
      - name: Verify Node-RED modules
        run: |
          ls -l node_modules | grep node-red
          node -e "console.log('✅ node-red-dashboard OK:', !!require.resolve('node-red-dashboard'))"

      # 🔹 Spakuj aplikację (w tym node_modules) w ZIP
      - name: Archive app for deployment
        run: |
          zip -r release.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip package
        run: unzip -o release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3CBA8E005282451DB2912CF76432B3DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBCF5118567E4A80BEFFD0BFB26A26C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A9E875950664853B8367FC1DF5368A7 }}

      # 🔹 Wymuś pełny deploy ZIP-a z node_modules
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'IoT-NodeRed-EnergyMeter'
          slot-name: 'Production'
          package: release.zip
